### ISSUE TITLE
Option to select different types of content?

### ISSUE THREAD

**Issue by richardtc** [collective/collective.newsflash#12]
Hi,

I'd like to use the product for blog content, but cannot see an option to select blogs (this was available in the older collections.newsticker product).

Cheers,
Richard

plone 4.2.1
collective.newsflash = 1.0

**Comment by hvelarde** [comment]
I think I do not understand your question; this package allows you to add a list of messages that are going to be displayed on a news ticker; this messages are simple text strings we are working on a new branch to allow the use of basic formating and hyperlinks).

[collective.newsticker](https://github.com/collective/collective.newsticker) is a different package that does almost the same, but instead of manually adding these messages, it uses the titles of the objects resulting from a catalog search using topics and IIRC collections.
